Repository OZ-Coding-School/oz_externship_fe_02_team3, pull requests merged in 2025-09, with the labels that each got.

#13 feat: modal base
  src/App.tsx
  src/components/modal/BaseModal.tsx
  src/components/modal/ModalFooter.tsx
  src/components/modal/ModalHeader.tsx
  src/components/modal/TestModal.tsx
  src/components/modal/index.ts
Labels: FEAT

#17 feat: application modal
  package-lock.json
  package.json
  src/App.tsx
  src/components/Button.tsx
  src/components/modal/FormField.tsx
  src/components/modal/TextareaWithCounter.tsx
  src/components/recruitment/application/ApplicationModal.tsx
  src/pages/TestModalPage.tsx
Labels: FEAT

#27 feat : 지원자관리 모달 구현
  src/components/StatusBadge.tsx
  src/components/modal/BaseModal.tsx
  src/components/modal/FormField.tsx
  src/components/modal/ModalHeader.tsx
  src/components/recruitment/application/ApplicationModal.tsx
  src/components/recruitment/common/Avatar.tsx
  src/components/recruitment/manage/ApplicantCard.tsx
  src/components/recruitment/manage/InfoRow.tsx
  src/components/recruitment/manage/ManageApplicantsModal.tsx
  src/data/applicants.ts
  src/pages/TestPage/TestApplicationModalPage.tsx
  src/utils/date.ts
Labels: FEAT

#65 refactor: 로고 컴포넌트에 SVG 적용 및 웹 접근성 개선
  package-lock.json
  package.json
  src/assets/images/logo_studyhub.svg
  src/components/header/components/Logo.tsx
  src/lib/index.ts
  src/lib/svg.d.ts
  vite.config.ts
Labels: REFACTOR

#73 chore: github actions CI 빌드 테스트 워크플로우 추가
  .github/workflows/build_test.yml
  src/components/recruitment/common/BackButton.tsx
  src/components/recruitment/common/NotificationBadge.tsx
  src/components/recruitment/common/RecDropDown.tsx
  src/components/recruitment/common/SelectRecDropDown.tsx
  src/components/recruitment/manage/RecManageFilter.tsx
  src/components/recruitment/manage/RecManageHeader.tsx
  src/components/recruitment/manage/RecManageList.tsx
  src/components/recruitment/manage/RecManageTotalCard.tsx
  src/pages/RecruitmentManage.tsx
Labels: CHORE

#80 refactor: 알림 아이콘 및 탭 스타일 cva 적용 및 HeaderUserSection 리팩토링 (#78)
  src/components/header/components/Navigation.tsx
  src/components/header/components/user-section/HeaderUserSection.tsx
  src/components/header/components/user-section/notificationIconClass.ts
  src/constants/ui.ts
  src/styles/fonts.css
Labels: REFACTOR

#19 feat: 강의목록 UI
  src/api/courseFetcher.ts
  src/components/course/ActionButton.tsx
  src/components/course/BookmarkButton.tsx
  src/components/course/CategoryFilter.tsx
  src/components/course/CourseCard.tsx
  src/components/course/CourseCardWithBookmark.tsx
  src/components/course/CourseGrid.tsx
  src/components/course/CourseStats.tsx
  src/components/course/EmptyState.tsx
  src/components/course/ErrorMessage.tsx
  src/components/course/FilterResetButton.tsx
  src/components/course/LoadMoreButton.tsx
  src/components/course/LoadingSpinner.tsx
  src/components/course/NavigationButton.tsx
  src/components/course/RecommendedSection.tsx
  src/components/course/SearchFilter.tsx
  src/components/course/SearchInput.tsx
  src/components/course/SectionHeader.tsx
  src/components/course/SelectableDropDown.tsx
  src/components/course/SortFilter.tsx
  src/components/header/Header.tsx
  src/constants/courses.ts
  src/constants/ui.ts
  src/hooks/course/useBookmark.ts
  src/hooks/course/useCourse.ts
  src/hooks/course/useCourseFilters.ts
  src/hooks/course/usePagination.ts
  src/hooks/course/useRecommendedCourses.ts
  src/hooks/useQueryParams.ts
  src/layouts/MainLayout.tsx
  src/mock/coursesData.ts
  src/pages/CoursesPage.tsx
  src/types/api.ts
  src/types/course.ts
  src/types/hooks.ts
  src/utils/courseComparators.ts
  src/utils/sortUtils.ts
Labels: FEAT

#84 refactor: PageLink 및 관련 컴포넌트 구조 개선(#83)
  src/components/header/components/user-section/HeaderUserSection.tsx
  src/components/page-link/PageLink.tsx
  src/components/page-link/linkClass.ts
  src/components/recruitment/manage/RecManageHeader.tsx
  src/pages/recruitment-page/Anonymous.tsx
Labels: REFACTOR

#91 feat: 커밋컨벤션을 자동으로 확인해주는 `husky` 세팅
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.ts
  package-lock.json
  package.json
Labels: FEAT

#88 feat: HeaderUserSection 에서 마이페이지와 로그아웃 할수 있는 ui 구현
  src/components/header/Header.tsx
  src/components/header/components/user-section/HeaderUserSection.tsx
Labels: FEAT

#90 refactor: Badge, DropDown, Header, HeaderUserSection, Avatar 컴포넌트에 cn 유틸 적용
  src/components/Badge.tsx
  src/components/DropDown.tsx
  src/components/header/Header.tsx
  src/components/header/components/user-section/HeaderUserSection.tsx
  src/components/recruitment/common/Avatar.tsx
Labels: REFACTOR

#107 refactor: DropDown 리팩토링
  src/components/commons/dropdown/DropDown.tsx
  src/components/commons/dropdown/DropDownOptionItem.tsx
  src/components/commons/dropdown/DropDownOptionList.tsx
  src/components/commons/header/components/notification-section/NotificationButton.tsx
  src/components/commons/header/components/notification-section/NotificationTabs.tsx
  src/components/commons/header/components/notification-section/NotificationsDropdown.tsx
  src/pages/test-page/TestUIPage.tsx
Labels: REFACTOR

#108 feat: 공고 목록 무한 스크롤링 구현
  src/App.tsx
  src/api/jobPosts.ts
  src/components/commons/JobPostCard.tsx
  src/components/recruitment/RecruitmentHeader.tsx
  src/components/recruitment/RecruitmentList.tsx
  src/components/recruitment/user-recruitment/Anonymous.tsx
  src/components/recruitment/user-recruitment/LoggedIn.tsx
  src/components/recruitment/user-recruitment/UserRecruitment.tsx
  src/hooks/useIntersectionObserver.ts
  src/hooks/useJobPosts.ts
  src/main.tsx
  src/mock/jobPosts.ts
  src/pages/RecruitmentPage.tsx
  src/types/jobPosts.ts
  tsconfig.app.json
  vite.config.ts
Labels: FEAT

#116 feat: 스터디 구인 공고 작성 `공고 마감 기한`, `스터디 그룹 소개` 기능 구
  package-lock.json
  package.json
  src/App.tsx
  src/components/commons/calendar/Calendar.style.css
  src/components/commons/calendar/Calendar.tsx
  src/components/commons/calendar/DateTriggerButton.tsx
  src/components/commons/calendar/data-trigger-button.style.ts
  src/components/recruitment-create/StudyIntroMarkdown.tsx
  src/components/recruitment-create/markdown-ui/IconBtn.tsx
  src/components/recruitment-create/markdown-ui/MdFooter.tsx
  src/components/recruitment-create/markdown-ui/MdPreview.tsx
  src/components/recruitment-create/markdown-ui/MdToolbar.tsx
  src/components/recruitment-create/markdown-ui/sanitizeSchema.ts
  src/components/recruitment-create/markdown-ui/useImageRender.tsx
  src/components/recruitment-create/markdown-ui/useMdCommands.ts
  src/pages/RecruitmentCreate.tsx
  src/pages/test-page/TestHub.tsx
  src/pages/test-page/TestUIPage.tsx
Labels: FEAT

#132 refactor: DropDown 컴포넌트 옵션 타입 객체 배열로 통일 및 타입 일관성 개선
  src/components/commons/dropdown/DropDown.tsx
  src/components/commons/dropdown/DropDownOptionList.tsx
  src/pages/test-page/TestUIPage.tsx
Labels: REFACTOR

#133 feat: 스터디 구인 공고 업로드 컴포넌트 기능 구현
  package-lock.json
  package.json
  src/components/recruitment-create/FileUploadBox.tsx
  src/components/recruitment-create/ImageUploadBox.tsx
  src/components/recruitment-create/uploadbox-ui/DottedBox.tsx
  src/components/recruitment-create/uploadbox-ui/FileList.tsx
  src/components/recruitment-create/uploadbox-ui/useUploader.ts
  src/pages/RecruitmentCreate.tsx
Labels: FEAT

#160 fix: 없는 강의 목록 확인시 로그인 관련 창이 사라지는 버그 수정
  src/components/course/AnonyMousCourses.tsx
  src/hooks/course/useCourse.ts
  src/pages/CoursesPage.tsx
  src/types/course.ts
Labels: FIX

#161 refactor: 북마크 버튼 반응형으로 만들기
  src/components/course/CourseCardWithBookmark.tsx
  src/components/course/CourseGrid.tsx
Labels: REFACTOR

#164 feat: 채팅 목록 mock 데이터 및 MSW API, React Query 연동 구현
  src/components/commons/chat/ChatFloatButton.tsx
  src/components/commons/chat/ChatItem.tsx
  src/components/commons/chat/ChatList.tsx
  src/components/commons/chat/Chatting.tsx
  src/components/commons/chat/Message.tsx
  src/components/commons/chat/MessageList.tsx
  src/components/commons/chat/ParticipantsList.tsx
  src/components/commons/chat/chat-header/ChatListHeader.tsx
  src/components/commons/chat/chat-header/ChatRoomHeader.tsx
  src/components/commons/header/components/notification-section/NotificationItem.tsx
  src/hooks/useChatting.ts
  src/hooks/useNotifications.ts
  src/mock/chatData.ts
  src/mock/chatListData.ts
  src/mock/handler.ts
  src/mock/notificationsData.ts
  src/mock/participants.ts
  src/types/chat.ts
  src/types/notification.ts
  src/types/participants.ts
Labels: FEAT

#184 fix: 구인 공고 작성 페이지 중앙정렬이 안맞는 현상 수정
  src/components/recruitment-create/RecCreateHeader.tsx
  src/components/recruitment-edit/RecEditHeader.tsx
  src/pages/RecruitmentCreate.tsx
  src/pages/RecruitmentEdit.tsx
Labels: FIX

#190 feat: 태그 선택 모달 구현 #159
  package-lock.json
  package.json
  src/api/tag.ts
  src/components/commons/LoadingSpinner.tsx
  src/components/commons/SearchBar.tsx
  src/components/commons/form/TextareaWithCounter.tsx
  src/components/commons/modal/ModalRoot.tsx
  src/components/commons/pagination/Pagination.tsx
  src/components/commons/tag/SelectedTag.tsx
  src/components/commons/tag/SelectedTagList.tsx
  src/components/commons/tag/TagCheckbox.tsx
  src/components/recruitment-create/RecCreateAdditionalInfo.tsx
  src/components/recruitment-create/tag-ui/SelectedTagSection.tsx
  src/components/recruitment-create/tag-ui/TagBox.tsx
  src/components/recruitment-create/tag-ui/TagCreateBox.tsx
  src/components/recruitment-create/tag-ui/TagResultSection.tsx
  src/components/recruitment-create/tag-ui/TagSearchModal.tsx
  src/components/recruitment-create/tag-ui/TagSection.tsx
  src/components/recruitment-manage/application/ApplicationModal.tsx
  src/hooks/tag/useSelectedTags.ts
  src/hooks/tag/useTagManager.ts
  src/mock/browser.ts
  src/mock/handlers/index.ts
  src/mock/handlers/notifications.ts
  src/mock/handlers/tags.ts
  src/pages/CoursesPage.tsx
  src/pages/test-page/TestUIPage.tsx
  src/styles/modal.ts
  src/types/badwords-ko.d.ts
  src/types/tag.ts
  src/validations/tag.ts
Labels: FEAT, REFACTOR

#193 refactor: 공고 상세 페이지 컴포넌트 수정
  src/components/commons/MarkdownComponents.tsx
  src/components/recruitment-create/RecCreateAdditionalInfo.tsx
  src/components/recruitment-detail/recruitment-attachment-list/RecruitmentAttachmentList.tsx
  src/components/recruitment-detail/recruitment-banner/BannerInfoBoxs.tsx
  src/components/recruitment-detail/recruitment-banner/BannerInfoList.tsx
  src/components/recruitment-detail/recruitment-banner/BannerTags.tsx
  src/components/recruitment-detail/recruitment-content/RecruitmentContent.tsx
  src/components/recruitment-detail/recuitment-lecture/RecuitmentLecture.tsx
Labels: REFACTOR

#198 feat: 공고 상세페이지 공유하기 기능 구현
  src/components/recruitment-detail/recruitment-banner/RecruitmentBanner.tsx
Labels: FEAT

#199 refactor: 공고 목록 페이지 리팩토링
  src/components/recruitment/RecruitmentHeader.tsx
  src/components/recruitment/RecruitmentList.tsx
  src/components/recruitment/recruitment-header/Anonymous.tsx
  src/components/recruitment/recruitment-header/LoggedIn.tsx
  src/components/recruitment/recruitment-header/RecruitmentHeader.tsx
  src/components/recruitment/recruitment-list/JobPostList.tsx
  src/components/recruitment/recruitment-list/RecruitmentList.tsx
  src/components/recruitment/srearch-filter-bar/FilterSection.tsx
  src/pages/RecruitmentPage.tsx
Labels: FEAT, REFACTOR

#203 refactor: 커스텀 마크다운 리팩토링
  src/components/recruitment-create/RecCreateContentSection.tsx
  src/components/recruitment-create/StudyIntroMarkdown.tsx
  src/components/recruitment-create/markdown-ui/mdImages.ts
  src/components/recruitment-create/markdown-ui/sanitizeSchema.ts
  src/components/recruitment-create/markdown-ui/useImageUploader.ts
  src/components/recruitment-create/markdown-ui/useMdCommands.ts
  src/components/recruitment-create/markdown-ui/useMdImageDnDPaste.ts
  src/components/recruitment-create/markdown-ui/useMdImageUpload.ts
  src/components/recruitment-edit/RecEditContentSection.tsx
  src/constants/recmdtoastmessage.ts
Labels: REFACTOR

#217 refactor: JobPostCard 컴포넌트 마우스 호버 액션 추가(#216)
  src/components/commons/JobPostCard.tsx
  src/components/commons/chat/ChatFloatButton.tsx
  src/components/commons/chat/ChatItem.tsx
  src/components/recruitment-manage/components/RecManageList.tsx
  src/components/recruitment/recruitment-list/JobPostList.tsx
Labels: REFACTOR

#220 feat: 채팅 목록 타임스탬프 유틸 수정
  src/components/commons/chat/ChatItem.tsx
  src/mock/chatListData.ts
  src/types/chat.ts
Labels: FEAT

#221 feat: 공고 목록 페이지 반응형 구현
  src/components/commons/JobPostCard.tsx
  src/components/commons/chat/ParticipantsList.tsx
  src/components/recruitment-detail/recruitment-banner/RecruitmentBanner.tsx
  src/components/recruitment/recruitment-header/Anonymous.tsx
  src/components/recruitment/recruitment-header/LoggedIn.tsx
  src/components/recruitment/recruitment-header/RecruitmentHeader.tsx
  src/components/recruitment/recruitment-list/JobPostList.tsx
  src/components/recruitment/srearch-filter-bar/SearchFilterBar.tsx
  src/components/recruitment/user-recruitment/Anonymous.tsx
  src/components/recruitment/user-recruitment/LoggedIn.tsx
  src/components/recruitment/user-recruitment/UserRecruitment.tsx
  src/constants/ui.ts
  src/hooks/useHorizontalScroll.ts
  src/pages/RecruitmentDetailPage.tsx
  src/pages/RecruitmentPage.tsx
Labels: FEAT

#226 feat: 스터디 구인 공고 작성 msw
  src/components/recruitment-create/RecCreateBasicInfo.tsx
  src/components/recruitment-create/RecCreateContentSection.tsx
  src/components/recruitment-create/RecCreateFooter.tsx
  src/hooks/useRecruitCreateForm.ts
  src/mock/recruitCreateHandler.ts
  src/pages/RecruitmentCreate.tsx
  src/utils/datetime.ts
Labels: FEAT

#227 refactor: 강의목록 페이지 리팩토링(#219)
  src/components/course/ErrorMessage.tsx
  src/components/course/course-content/BookmarkButton.tsx
  src/components/course/course-content/CourseCard.tsx
  src/components/course/course-content/CourseContent.tsx
  src/components/course/course-content/CourstList.tsx
  src/components/course/course-content/EmptyCourses.tsx
  src/components/course/course-content/ReviewSection.tsx
  src/components/course/course-content/StarRating.tsx
  src/components/course/course-filter-bar/CourseStats.tsx
  src/components/course/course-filter-bar/FilterResetButton.tsx
  src/components/course/course-filter-bar/FilterSection.tsx
  src/components/course/course-filter-bar/SearchFilter.tsx
  src/components/course/course-header/CourseHeader.tsx
  src/components/course/course/CourseCardWithBookmark.tsx
  src/components/course/course/CourseGrid.tsx
  src/components/course/course/UserCourseSection.tsx
  src/components/course/filters/CategoryFilter.tsx
  src/components/course/filters/SearchFilter.tsx
  src/components/course/filters/SortFilter.tsx
  src/components/course/sections/RecommendedSection.tsx
  src/components/course/ui/ActionButton.tsx
  src/components/course/ui/LoadMoreButton.tsx
  src/components/course/ui/NavigationButton.tsx
  src/components/course/ui/SearchInput.tsx
  src/components/course/ui/SectionHeader.tsx
  src/components/course/ui/SelectableDropDown.tsx
  src/components/course/user-course/Anonymous.tsx
  src/components/course/user-course/LoggedIn.tsx
  src/components/course/user-course/UserCourse.tsx
  src/constants/ui.ts
  src/mock/reviewData.ts
  src/pages/CoursesPage.tsx
Labels: REFACTOR

#224 feat: 공고수정 msw
  src/api/recruitments.edit.ts
  src/components/recruitment-edit/RecEditBasicInfo.tsx
  src/components/recruitment-edit/RecEditFooter.tsx
  src/constants/receditmessage.ts
  src/mock/handlers/index.ts
  src/mock/recruitmentEditHandlers.ts
  src/mock/recruitments.store.ts
  src/pages/RecruitmentEdit.tsx
  src/utils/recEdit.ts
Labels: FEAT

#233 refactor: SearchFilter 디자인에 border 누락되어있던거 수정
  src/components/course/course-filter-bar/SearchFilter.tsx
Labels: REFACTOR

#235 feat: 404 페이지 구현
  src/App.tsx
  src/pages/NotFoundPage.tsx
Labels: FEAT

#245 feat: 스터디 지원서 제출 API 연동
  src/api/application.ts
  src/api/tag.ts
  src/components/recruitment-detail/recruitment-banner/RecruitmentBanner.tsx
  src/components/recruitment-manage/application/ApplicationModal.tsx
  src/mock/handlers/applications.ts
  src/mock/handlers/index.ts
  src/mock/handlers/tags.ts
  src/pages/test-page/TestModalPage.tsx
  src/types/applicant.ts
Labels: FEAT

#248 docs:README 업데이트
  README.md
Labels: DOCS

#249 feat: 알림 버튼이 로그인시에만 보이도록 수정
  src/App.tsx
  src/components/commons/chat/Chatting.tsx
  src/components/commons/header/components/user-section/HeaderUserSection.tsx
  src/components/commons/header/components/user-section/UserMenu.tsx
  src/constants/apiendpoint.ts
  src/hooks/useNotifications.ts
  src/store/auth.ts
Labels: FEAT

#253 feat: 헤더의 UserMenu 액션 구현(#252)
  src/api/api.ts
  src/components/commons/header/components/user-section/AuthMenu.tsx
  src/components/commons/header/components/user-section/HeaderUserSection.tsx
  src/components/commons/header/components/user-section/UserMenu.tsx
  src/constants/apiendpoint.ts
  src/hooks/useMediaQuery.ts
  src/store/auth.ts
Labels: FEAT

#257 feat: 스터디 참여 알림과 채팅방 연결
  src/components/commons/chat/Chatting.tsx
  src/components/commons/header/components/notification-section/NotificationButton.tsx
  src/components/commons/header/components/notification-section/NotificationItem.tsx
  src/components/commons/header/components/notification-section/NotificationsDropdown.tsx
Labels: FEAT

#259 feat: 알림목록 무한스크롤 기능 추가(#258)
  src/components/commons/header/components/notification-section/NotificationsDropdown.tsx
  src/hooks/useNotifications.ts
Labels: FEAT

#261 refactor: 공고 목록에 여백 추가
  src/pages/RecruitmentPage.tsx
Labels: REFACTOR

#268 feat: 북마크 로그인 관련 트리거 추가
  src/components/recruitment-detail/recruitment-banner/RecruitmentBanner.tsx
Labels: FEAT
